### ISSUE TITLE
There's no need to fork this project

### ISSUE THREAD

**Issue by dapetcu21** [C0bra5/starbound-autocomplete-lua#1]
Hi! I notice you're trying to add the starbound API to autocomplete-lua. There's no need for you to make a modified version of this project. There's a provider API for 3rd party extensions. There are docs for it in the README. You can use [Defold IDE](https://atom.io/packages/defold-ide) as an example or any of the built-in providers bundled with autocomplete-lua (check the README).

**Comment by C0bra5** [comment]
here are the reasons why I went with a fork/separate project instead of using/making a 3rd party API extension:

* I have no intention to ever push back the changes as all the changes I have and plan to make are to improve the starbound modding workflow, not the general LUA workflow.
* I wanted it to display the return and argument datatypes for a function. The original package didn't show any of this. Plus some stuff with the variants wasn't working as well as I needed it to.
![https://puu.sh/yZEjv/0ae6e61c23.png](https://puu.sh/yZEjv/0ae6e61c23.png)
* I wanted the starbound documentation to be the _**only**_ documentation available because my user base is very likely use the plugin (and potentially atom itself) for starbound modding only and not for general LUA.
* I don't want to redistribute a custom luarc file because I want my users to be able to have their own luarc to document their own APIs and have it show up on the autocomplete results. Plus, I'm not sure anyone likes modifying a 7000 lines long file.
* I want the documentation to come with the plugin and make it easier to maintain. I had a lot of documentation to write and a lot of work ahead of me, I added the stuff I needed and customised the rest.

#### **TLDR; In short, I wanted to make it simpler to use and maintain on both me and the end user as I wasn't going to write 7000 lines of documentation if I couldn't at least make it a bit easier on my self. Plus there is the fact that I want to add some functionality that the original package didn't have. I cannot add the functionality using a third party extension as the changes are related to how the recommendations are stored and how they are shown to the user. Both of those things cannot be done through a third party extension, but can be done by modifying the package(the typedef file needed to be updated to show the return and parameter types properly).**

The main user base for this package is new-ish to programming so I want them to have a smooth as possible experience. Therefore, it needs to just work, and so far the package has succeded at that fairly well.

**Comment by dapetcu21** [comment]
Those are perfectly valid reasons. Making a provider obviates the need for a `.luarc`, though and works in tandem with a user-provided `.luarc`.

**Comment by C0bra5** [comment]
I'll be closing this issue in a day or so, as I don't believe there is anything more to be said about this.
I've updated my previous response better describe why I chose to make a fork instead of a third party as I feel the tldr; didn't really explain the main reason why I made a fork instead of an extension
